### ISSUE TITLE
ещё один ползунок на первый таб

### ISSUE THREAD

**Issue by admzzz** [agricolamz/zaliznyak#2]
вставить 13ой строкой в ui.R:
sliderInput("l.symbol_after", "Отступ после ударного гласного для применения РЛ:",
min=0, max=5, value=0),

в server.R 14ая строка:
 query_f_fragment <- str_sub(input$query, str_vowel_id+1+l.symbol_after, nchar(input$query))

**Comment by agricolamz** [comment]
Нет, это не верно.
